name: Pull request

on: pull_request

jobs:
    dotnet-format-fix:
      runs-on: ubuntu-latest

      steps:
        - name: Dump GitHub context
          run: echo "$GITHUB_CONTEXT"
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}

        - name: Install dotnet-format
          run: |
            echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
            dotnet tool install -g dotnet-format

        - name: Checkout repo
          uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

        - name: Run dotnet format
          id: format
          uses: xt0rted/dotnet-format@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            only-changed-files: true
            action: "fix"

        - name: Dump format step
          run: echo "$FORMAT_STEP"
          env:
            FORMAT_STEP: ${{ toJson(steps.format) }}

        - name: Commit files
          if: steps.format.outputs.has-changes == 'true'
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -a -m 'Automated dotnet-format update

            Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

        - name: Push changes
          if: steps.format.outputs.has-changes == 'true'
          uses: ad-m/github-push-action@v0.5.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.head_ref }}
